-- Private Storage bucket for audit source documents (estimate PDFs +
-- photos). Path convention (enforced by app code, not the DB):
--   {contractor_id}/{claim_id}/{audit_id}/estimate.pdf
--   {contractor_id}/{claim_id}/{audit_id}/photos/*
-- Per BON_BUILD_SEQUENCE.md Phase A2. Uploads happen client-side via
-- signed URLs generated by a server-side function — this migration only
-- creates the bucket and its access policy, not the signing function.
insert into storage.buckets (id, name, public)
values ('claim-docs', 'claim-docs', false)
on conflict (id) do nothing;

-- Same trust model as every other CRM-internal table: no auth system
-- yet, so permissive policy scoped to just this bucket.
create policy "allow all - claim-docs" on storage.objects
  for all
  using (bucket_id = 'claim-docs')
  with check (bucket_id = 'claim-docs');
